# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@react-native-community/slider'
      - dependency-name: '@shopify/react-native-skia'
      - dependency-name: 'react-native'
      - dependency-name: 'react-native-gesture-handler'
      - dependency-name: 'react-native-reanimated'
      - dependency-name: 'react-native-safe-area-context'
      - dependency-name: 'react-native-web'
      - dependency-name: 'react-native-webview'
      - dependency-name: '@react-navigation/native'
      - dependency-name: 'react-native-screens'
      - dependency-name: '@react-native-async-storage/async-storage'
      - dependency-name: 'expo-blur'
      - dependency-name: 'expo-constants'
      - dependency-name: 'expo-font'
      - dependency-name: 'expo-linking'
      - dependency-name: 'expo-router'
      - dependency-name: 'expo-symbols'
      - dependency-name: 'expo-system-ui'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react'
      - dependency-name: 'eslint-config-expo'
